version: "3.3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
            AMQP_URL: amqp://guest:guest@rabbitmq:5672
        ports:
            - "8083:3000"
        networks:
            - rabbitmq_nodejs

    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        networks:
            - rabbitmq_nodejs

    rabbitmq:
        image: rabbitmq:latest
        ports:
            - "15672:15672"
            - "5673:5672"
        networks:
            - rabbitmq_nodejs

networks:
    rabbitmq_nodejs:
        driver: bridge